<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>48587114-f216-479f-a5b5-12a3bfba4670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'المزيد')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.solid-part.charge-part.mt-5 > div.container > div.solid-part-product > div.row > div.col-md-12 > div.row.justify-content-md-center > div.col-md-2.mt-3 > a.main-btn.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92e88701-9af9-4d06-b23e-86719fc57e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://new.ly-card.com/services/recharge</value>
      <webElementGuid>62c21207-f68b-48f8-aa47-31f3863e6b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-btn w-100</value>
      <webElementGuid>c5b2ef7c-2600-4f9d-8311-40f90fa29048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    المزيد
                                </value>
      <webElementGuid>9b65654c-07f9-469d-b635-f5a8fd7dae95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;global-main&quot;]/section[@class=&quot;solid-part charge-part mt-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;solid-part-product&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row justify-content-md-center&quot;]/div[@class=&quot;col-md-2 mt-3&quot;]/a[@class=&quot;main-btn w-100&quot;]</value>
      <webElementGuid>e02243f0-adcf-4b50-844b-cf46d6fdefb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'المزيد')])[2]</value>
      <webElementGuid>07f71da0-f059-4e33-ada0-5ff09bc04633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بطاقات بلايستيشن'])[1]/following::a[1]</value>
      <webElementGuid>6591becb-9995-4686-bb45-0a683614dd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بطاقات ايتونز'])[1]/following::a[2]</value>
      <webElementGuid>7fb27db1-ca81-4d2a-927e-a40b9ade7d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خدمات الألعاب'])[1]/preceding::a[1]</value>
      <webElementGuid>668cc47e-98e4-49e7-b20a-7bd83255f2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ستارميكر'])[1]/preceding::a[1]</value>
      <webElementGuid>8f369c47-0b2a-42ba-a862-56826cdb6d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://new.ly-card.com/services/recharge')])[2]</value>
      <webElementGuid>31872f7c-cc24-46d2-a7a4-9fb1ba115362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div[2]/div/div[5]/div/div/a</value>
      <webElementGuid>34997bb1-95e1-4623-aad5-fefb6298b9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://new.ly-card.com/services/recharge' and (text() = '
                                    المزيد
                                ' or . = '
                                    المزيد
                                ')]</value>
      <webElementGuid>d533690a-3e58-4b54-9129-27386df78231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
